try another thing

diff --git a/.github/workflows/pr_workflow.yml b/.github/workflows/pr_workflow.yml
--- a/.github/workflows/pr_workflow.yml
+++ b/.github/workflows/pr_workflow.yml
@@ -18,24 +18,44 @@ permissions:
   statuses: none
 
 jobs:
+  pr-label:
+    runs-on: ubuntu-latest
+    name: Label PR
+    steps:
+      - uses: actions/labeler@main
+        with:
+          configuration-path: ".github/labeller.yml"
+          repo-token: "${{ secrets.GITHUB_TOKEN }}"
+          sync-labels: true
+
+  unit_tests:
+    runs-on: ubuntu-latest
+    name: Run unit tests
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Run unit tests
+        run: docker-compose up unit-tests
+        id: unit_tests
+
   branch_name:
     runs-on: ubuntu-latest
     name: Extract branch name
     outputs:
-      raw_branch: ${{ steps.extract_branch.outputs.branch }}
-      sanitised_branch: ${{ steps.extract_branch.outputs.branchsane }}
+      raw_branch: ${{ steps.extract_branch.outputs.branch_raw }}
+      formatted_branch: ${{ steps.extract_branch.outputs.branch_formatted }}
     steps:
       - name: Extract branch
         shell: bash
         run: |
-          echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}})"
-          echo "##[set-output name=branchsane;]$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} | tr -cd '[:alnum:]')"
+          echo "##[set-output name=branch_raw;]$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}})"
+          echo "##[set-output name=branch_formatted;]$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} | tr -cd '[:alnum:]')"
         id: extract_branch
-      - name: Dump GitHub context
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: |
-          echo "$GITHUB_CONTEXT"
+#      - name: Dump GitHub context
+#        env:
+#          GITHUB_CONTEXT: ${{ toJson(github) }}
+#        run: |
+#          echo "$GITHUB_CONTEXT"
 
   create_tags:
     name: Create Tags
@@ -46,57 +66,82 @@ jobs:
     secrets:
       source_github_token: ${{ secrets.GITHUB_TOKEN }}
 
-#  unit_tests:
-#    runs-on: ubuntu-latest
-#    name: Run unit tests
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v2
-#      - name: Run unit tests
-#        run: docker-compose up unit-tests
-#        id: unit_tests
+  docker_build_scan_push:
+    name: Build, Scan and Push
+    needs: ['create_tags']
+    uses: ./.github/workflows/docker_build.yml
+    with:
+      lambda_names: '[{"name": "deputy-reporting-lambda", "path": "lambda_functions/v2"}, {"name": "deputy-reporting-mock-sirius", "path": "mock_sirius"}]'
+      tag: ${{ needs.create_tags.outputs.version_tag }}
+    secrets:
+      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
 
-#  create_release:
-#    name: Create Release
-#    needs: ['create_tags']
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v2
-#      - name: Create a release
-#        id: create_release
-#        uses: actions/create-release@v1
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
-#        with:
-#          tag_name: ${{ needs.create_tags.outputs.version_tag }}
-#          release_name: Release ${{ needs.create_tags.outputs.version_tag }}
-#          body: |
-#            Changes in this Release
-#            - Jim change
-#            - Second Change
-#          draft: false
-#          prerelease: false
-#  docker_build_scan_push:
-#    name: Build, Scan and Push
-#    needs: ['create_tags']
-#    uses: ./.github/workflows/docker_build.yml
-#    with:
-#      lambda_names: '[{"name": "deputy-reporting-lambda", "path": "lambda_functions/v2"}, {"name": "deputy-reporting-mock-sirius", "path": "mock_sirius"}]'
-#      tag: ${{ needs.create_tags.outputs.version_tag }}
-#    secrets:
-#      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
-#      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+  terraform_plan_apply_with_mock:
+    name: Terraform Environment with Sirius mock
+    needs: ['docker_build_scan_push', 'unit_tests', 'create_tags', 'branch_name']
+    uses: ./.github/workflows/terraform_job.yml
+    with:
+      terraform_path: 'terraform/environment'
+      image_tag: ${{ needs.create_tags.outputs.version_tag }}
+      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
+      mock_sirius: "1"
+    secrets:
+      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
 
-#  terraform_plan_apply:
-#    name: Terraform Environment
-#    needs: ['docker_build_scan_push']
-#    uses: ./.github/workflows/terraform_job.yml
-#    with:
-#      terraform_path: 'terraform/environment'
-#      image_tag: ${{ needs.create_tags.outputs.version_tag }}
-#      workspace: ${{ needs.branch_name.outputs.sanitised_branch }}
-##      {{ needs.branch_name.outputs.raw_branch_name }}
-#    secrets:
-#      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
-#      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+  integration_tests:
+    name: Integration tests
+    runs-on: ubuntu-latest
+    needs: ['terraform_plan_apply_with_mock', 'branch_name']
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Build integration tests container
+        run: docker-compose -f docker-compose.yml build integration-tests
+        id: build_integration_tests
+      - name: Run integration tests
+        run: |
+          docker-compose -f docker-compose.yml up integration-tests
+          export DOCKER_EXIT_CODE=$(docker inspect $(docker ps -a | head -2 | tail -1 | awk '{print $1}') --format='{{.State.ExitCode}}')
+          if [ "$DOCKER_EXIT_CODE" = "0" ]
+          then
+            echo "Tests passed"
+          else
+            echo "Tests failed"
+            exit 1
+          fi
+        env:
+          TF_WORKSPACE: ${{ needs.branch_name.outputs.formatted_branch }}
+          CI: "true"
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+        id: run_integration_tests
+
+  terraform_plan_apply:
+    name: Terraform Environment
+    needs: ['integration_tests', 'create_tags', 'branch_name']
+    uses: ./.github/workflows/terraform_job.yml
+    with:
+      terraform_path: 'terraform/environment'
+      image_tag: ${{ needs.create_tags.outputs.version_tag }}
+      workspace: ${{ needs.branch_name.outputs.formatted_branch }}
+    secrets:
+      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+
+  workflow_complete:
+    name: Terraform Environment
+    runs-on: ubuntu-latest
+    needs: ['terraform_plan_apply', 'branch_name']
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Protect Workspace
+        run: terraform-workspace-manager -register-workspace=$TF_WORKSPACE -time-to-protect=4 -aws-account-id=288342028542 -aws-iam-role=integrations-ci
+        env:
+          TF_WORKSPACE: ${{ needs.branch_name.outputs.formatted_branch }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
+      - name: Workflow complete message
+        run: echo "Workflow Complete"
